pre-commit:
  jobs:
    - name: linters
      group:
        parallel: true
        jobs:
          - name: dprint
            glob: "*.{json,jsonc,md,yaml}"
            run: mise exec -- dprint fmt {staged_files}
          - name: shell-tools
            glob: vault-token-helper-secret-tool
            group:
              jobs:
                - name: shfmt
                  run: mise exec -- shfmt --write --simplify {staged_files}
                - name: shellcheck
                  run: mise exec -- shellcheck --format=gcc {staged_files}
    - name: hook-made-changes
      run: |-
        if test -n "${CI-}"; then
          git diff --exit-code {staged_files}
        else
          git diff --quiet {staged_files}
        fi
        rc=$?
        test $rc -eq 0 || echo "error: found files modified by hooks" >&2
        exit $rc
