pre-commit:
  commands:
    dprint:
      run: >-
        wrun
        -url darwin/amd64=https://github.com/dprint/dprint/releases/download/0.46.1/dprint-x86_64-apple-darwin.zip#sha256-cdea84bce1d84c26e8eced2265d246b79a849ec2e7d1377d98dd7bdb21c7ce83
        -url darwin/arm64=https://github.com/dprint/dprint/releases/download/0.46.1/dprint-aarch64-apple-darwin.zip#sha256-f3ff4faef83d14c3b4ae262e79a40d4e0fc3fa1903d0b6e9b82f0b25b00e9499
        -url linux/amd64=https://github.com/dprint/dprint/releases/download/0.46.1/dprint-x86_64-unknown-linux-musl.zip#sha256-4a7d6fa6b920ab150f580965556086cdd7992e07078e627ab9a9d1c3bd30ba85
        -url linux/arm64=https://github.com/dprint/dprint/releases/download/0.46.1/dprint-aarch64-unknown-linux-musl.zip#sha256-e2b6d87167d21f1f01571790e79526ef9caff3b8b75f5cac348c4f06f60a8c16
        -url windows/amd64=https://github.com/dprint/dprint/releases/download/0.46.1/dprint-x86_64-pc-windows-msvc.zip#sha256-74e5ab38c744d5903862c2b5174d0fef9759b5506da775e1fb93b6a68c63101d
        -archive-exe-path dprint
        --
        fmt
        --allow-no-files
        {staged_files}
        && git diff --exit-code {staged_files}
    shellcheck:
      glob: vault-token-helper-secret-tool
      run: >-
        wrun
        -url darwin/arm64=https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.darwin.aarch64.tar.xz#sha256-bbd2f14826328eee7679da7221f2bc3afb011f6a928b848c80c321f6046ddf81
        -url darwin/amd64=https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.darwin.x86_64.tar.xz#sha256-ef27684f23279d112d8ad84e0823642e43f838993bbb8c0963db9b58a90464c2
        -url linux/amd64=https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz#sha256-6c881ab0698e4e6ea235245f22832860544f17ba386442fe7e9d629f8cbedf87
        -url linux/arm64=https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.aarch64.tar.xz#sha256-324a7e89de8fa2aed0d0c28f3dab59cf84c6d74264022c00c22af665ed1a09bb
        -url windows/amd64=https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.zip#sha256-eb6cd53a54ea97a56540e9d296ce7e2fa68715aa507ff23574646c1e12b2e143
        -archive-exe-path windows/*=shellcheck.exe
        -archive-exe-path shellcheck-v0.10.0/shellcheck
        --
        --format=gcc
        {staged_files}
    shfmt:
      glob: vault-token-helper-secret-tool
      run: >-
        wrun
        -url darwin/amd64=https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_darwin_amd64#sha256-c0218b47a0301bb006f49fad85d2c08de23df303472834faf5639d04121320f8
        -url darwin/arm64=https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_darwin_arm64#sha256-1481240d2a90d4f0b530688d76d4f9117d17a756b6027cfa42b96f0707317f83
        -url linux/amd64=https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64#sha256-27b3c6f9d9592fc5b4856c341d1ff2c88856709b9e76469313642a1d7b558fe0
        -url linux/arm64=https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_arm64#sha256-27e1f69b0d57c584bcbf5c882b4c4f78ffcf945d0efef45c1fbfc6692213c7c3
        -url windows/amd64=https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_windows_amd64.exe#sha256-91230a6d2d4dbb52e9c0bb134acba526f7880bfd3dfd1ffdde66e9f393d7a646
        --
        --write --simplify
        {staged_files}
        && git diff --exit-code {staged_files}
