repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.3.0]
        entry: shfmt
        args: [-w, -s]
        types: [shell]
        minimum_pre_commit_version: 2.4.0
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
        args: [-f, gcc]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint

ci:
  autoupdate_commit_msg: "chore: pre-commit.ci autoupdate"
