repos:
  - repo: https://github.com/scop/pre-commit-shfmt-workaround
    rev: v0
    hooks:
      - id: shfmt
        name: shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]
        entry: shfmt
        args: [-w, -s]
        types: [shell]
  - repo: https://github.com/ryanrhee/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
        args: [-f, gcc]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.0
    hooks:
      - id: markdownlint
