repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-f, gcc]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: testing
        name: testing
        language: system
        entry: sh -c "ls -la /etc/resolv.conf; echo xxx; cat /etc/resolv.conf; echo xxx; exit 1"
      - id: testing2
        name: testing2
        language: system
        entry: sh -c "env; exit 1"

ci:
  autoupdate_commit_msg: "chore: pre-commit.ci autoupdate"
