repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.3.1]
        entry: shfmt
        args: [-w, -s]
        types: [shell]
        minimum_pre_commit_version: 2.4.0
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
        args: [-f, gcc]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier

ci:
  autoupdate_commit_msg: "chore: pre-commit.ci autoupdate"
