name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - run: lefthook run pre-commit --all-files --no-tty
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          commit-message: "chore: autofix.ci automated fixes"
