name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
      - run: lefthook run pre-commit --all-files --no-tty
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          commit-message: "chore: autofix.ci automated fixes"
