name: Main push and PR checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # No caching as we're expected to run rarely
      - name: Install dependencies and run checks
        run: |
          set -euxo pipefail
          npm install -g lefthook
          python3 -m pip install --no-cache-dir wrun-py
          lefthook run pre-commit --all-files --force

