name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - run: lefthook run commits-on-pr-branch --no-tty
