name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
      - run: lefthook run commits-on-pr-branch --no-tty
